name: build and test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SHELL: /usr/bin/bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: musl
      run: sudo apt-get install musl-tools
    - name: rust nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          # Musl for integ tests; they need static linking to run cause mount
          # namespaces are hard.
          target: x86_64-unknown-linux-musl
          components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: sudo -E $(which cargo) test --verbose -- --nocapture
